### ISSUE TITLE
charmap error

### ISSUE THREAD

**Issue by coIev** [capture0x/XSS-LOADER#2]
C:\Users\king\Desktop\XSS-LOADER-master\XSS-LOADER-master>python3 payloader.py
Traceback (most recent call last):
  File "payloader.py", line 29, in <module>
    class payloadsList:
  File "payloader.py", line 31, in payloadsList
    aa = f.read()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x9d in position 854: character maps to <undefined>

**Comment by capture0x** [comment]
Issues fixed. This is encoding problem. If you are trying to use on Windows probably didn't work.  Because its writed for Linux based os. It's include bash color codes. So bash colors didn't work for Windows.  May be we'll upgrade for Windows. Thank you for report! (:

**Comment by capture0x** [comment]
Hi, we're edited for Windows (:
You can reach below link:
https://github.com/capture0x/XSS-LOADER-for-WINDOWS
